version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      day: "friday"
      time: "17:00"
      timezone: "Europe/London"
      interval: "weekly"
    assignees:
      - "ascopes"
    labels:
      - "ci"
      - "tiny"
      - "housekeeping"

  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      day: "friday"
      time: "17:00"
      timezone: "Europe/London"
      interval: "weekly"
    assignees:
      - "ascopes"
    labels:
      - "maven"
      - "tiny"
      - "housekeeping"
