name: Pull request build
on:
  pull_request:
    branches: [ "**" ]
    types: [ opened, synchronize ]

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/_run-tests.yml
  javadocs:
    name: JavaDocs
    uses: ./.github/workflows/_generate-javadocs.yml
  compliance:
    name: Compliance
    uses: ./.github/workflows/_check-compliance.yml
